### ISSUE TITLE
JSON source not being processed in converter

### ISSUE THREAD

**Issue by kows** [limbo-works/Limbo.Umbraco.Tables#1]
https://github.com/limbo-works/Limbo.Umbraco.Tables/blob/9f1c2cfc6431b251dc4eda8e8458f553da4bd3c6/src/Limbo.Umbraco.Tables/PropertyEditors/TablesDataValueConverter.cs#L30

I'm working on a setup where this editor is used inside the new v11 Block Grid combined with the custom Razor previews.
In this situation the argument 'object? source' for method ConvertSourceToIntermediate contains a JObject iso string and is being ignored completely.

I would propose to make a change similar to what I've seen for the MultipleTextString converter to support multiple formats.
https://github.com/umbraco/Umbraco-CMS/pull/11456

**Comment by abjerner** [comment]
Hi @kows and sorry for the lack of reply

Can you provide some information on how to reproduce this issue? I haven't really used the block grid yet, but am I correct to say that Razor previews are not something that is supported in Umbraco by default? Are you using a third-party package for this?

**Comment by abjerner** [comment]
Although I still think this may be due some custom code that handles the parsing different from Umbraco's, the property value converter was updated for [**v1.0.3**](https://github.com/limbo-works/Limbo.Umbraco.Tables/releases/tag/v1.0.3), which was released the same day of my last comment.

As I haven't heard back from you, and the issue should be fixed, I'm closing the issue.
