### ISSUE TITLE
Feature: Highlight column or row

### ISSUE THREAD

**Issue by cf-marc** [limbo-works/Limbo.Umbraco.Tables#15]
Hello

Is it possible to add a checkbox for a column or row to highlight the element?

**Comment by abjerner** [comment]
Hi @cf-marc 

This is currently not supported or something we're actively working on. I've marked this is an idea, as it could be a feature we would look at in the future.

**Comment by abjerner** [comment]
Hi again

We're closing this issue as it's not something we have any active plans working. Even when closed, we can still find it later via the [`status/idea`](https://github.com/limbo-works/Limbo.Umbraco.Tables/issues?q=label%3Astatus%2Fidea) label.
