### ISSUE TITLE
Ability to configure Wysiwyg

### ISSUE THREAD

**Issue by jpkeisala** [limbo-works/Limbo.Umbraco.Tables#17]
It would be nice to be able to configure RTE somehow. Ideally having it from  Richtext editor Data Types?

**Comment by abjerner** [comment]
Hi @jpkeisala 

Although not accepted and merged yet, there is a PR for this here: https://github.com/limbo-works/Limbo.Umbraco.Tables/pull/14

You can follow the progress there, so I'm closing this issue.
