### ISSUE TITLE
Add ability move columns like we can move rows

### ISSUE THREAD

**Issue by Eaglef90** [limbo-works/Limbo.Umbraco.Tables#19]
We can currently move rows around to change data order but we can't do it for columns. I have found myself having to add a column to around 200 tables and since I can't drag around the columns like we can with rows this is causing a LOT of copy/past work to move data around. Could the ability to move columns around be added?

**Comment by abjerner** [comment]
Hi @Eaglef90 

I'll mark this as an idea, but it's not something we'll actively be working on. At least not for now.

Currently the UI supports sorting in a single dimension (moving rows up and down). Being able to sort in two different dimensions adds another level of complexity, and it might not be possible with jQuery UI, which we're currently using.
