### ISSUE TITLE
Changing the rich text editor

### ISSUE THREAD

**Issue by Noor-alghadeer** [limbo-works/Limbo.Umbraco.Tables#20]
Hello,
Is it possible to change the cell's rich text editor configurations?

**Comment by abjerner** [comment]
Hi @Noor-alghadeer 

This is currently possible in `v1.1.0-alpha001`:

https://github.com/limbo-works/Limbo.Umbraco.Tables/releases/tag/v1.1.0-alpha001

It's a pre-release, but  `v1.1.0` will be released either a bit later today, or some time text week 😉
