### ISSUE TITLE
Setting allowUseFirstRowAsHeader doesn't yield checkbox in editor

### ISSUE THREAD

**Issue by craigagnew** [limbo-works/Limbo.Umbraco.Tables#23]
## Summary
When configuring the Limbo Tables data type in Umbraco, when only `allowUseFirstRowAsHeader` is set the toolbar containing these options in the Property Editor is not shown. 

## Version
1.1.1

## Steps to reproduce

1. Install the package to an Umbraco instance
2. Configure the Data Type for Limbo Tables to only have "Allow 'Use first row as header' option" checked
3. Add as property of a content type
4. Edit the content type in the content section
5. Observe that the toolbar doesn't display

## Screenshots

![chrome_rhFHX2JhCQ](https://github.com/limbo-works/Limbo.Umbraco.Tables/assets/5082297/91d15234-8bc0-4470-899c-9f50786ef9a5)

![chrome_R9v3g5naNe](https://github.com/limbo-works/Limbo.Umbraco.Tables/assets/5082297/0e2c0334-48a6-461d-8c55-e80bfe725e9f)

![chrome_BHGRyZZ0gU](https://github.com/limbo-works/Limbo.Umbraco.Tables/assets/5082297/05625509-327d-45f1-b725-a591c9a2aa3a)

## Expected behaviour
Setting only this option yields the "Use first row as header" option in the property editor

## System info
Umbraco v10.7.0

**Comment by abjerner** [comment]
@craigagnew thanks for reporting 👍 

The Angular view for the property editor had a check for `vm.vm.allowUseFirstRowAsHeader`, which should instead be just `vm.allowUseFirstRowAsHeader`. Unfortunately I hadn't spotted this when testing the package.

I've pushed a new release that fixes this: https://github.com/limbo-works/Limbo.Umbraco.Tables/releases/tag/v1.1.2

**Comment by craigagnew** [comment]
Awesome, thanks @abjerner!
