### ISSUE TITLE
Umbraco V13 support?

### ISSUE THREAD

**Issue by AaronSadlerUK** [limbo-works/Limbo.Umbraco.Tables#26]
Will this package be getting updated to V13?

**Comment by abjerner** [comment]
@AaronSadlerUK due to general busyness, I don't have an ETA for when this package will be updated.

Right now this issue is also a show stopper:

https://github.com/umbraco/Umbraco-CMS/issues/15474

**Comment by FrancescoMusmanno** [comment]
Hi @abjerner are there any news about the package update for umbraco v13?
The stopper: https://github.com/umbraco/Umbraco-CMS/issues/15474
has been fixed in: https://github.com/umbraco/Umbraco-CMS/pull/15556

Thank you in advance for the answer

**Comment by iuliaionescu** [comment]
Hi, I am looking forward to the update as well! Thank you @abjerner

**Comment by Debbinson** [comment]
Hello, I also desperately need the upgrade for the Umbraco 13 version! :) Thank you in advance @abjerner

**Comment by abjerner** [comment]
I'm still hit by busyness, but I managed to find a bit of time, and I've now pushed a beta release targeting Umbraco 13:

https://github.com/limbo-works/Limbo.Umbraco.Tables/releases/tag/v13.0.0-beta001

I've tested it briefly, and everything seems to work, but arguable I should do some more testing before pushing a stable release.

There are also things that won't be covered in the stable 13.0.0 release - eg. improving the output for the content delivery API.

**Comment by aguyfromdenmark** [comment]
Any indications of when the full release of v13 will be out, @abjerner ?

**Comment by abjerner** [comment]
@aguyfromdenmark hopefully within this week. I haven't tested the package any further since the beta, so any feedback would be helpful. Eg. if it works perfectly, or you've encountered any issues.

**Comment by abjerner** [comment]
I should probably have closed this back in April when [`v13.0.0`](https://github.com/limbo-works/Limbo.Umbraco.Tables/releases/tag/v13.0.0) was released 🤔
