### ISSUE TITLE
Entire JSON structure is getting entered into External Examine index

### ISSUE THREAD

**Issue by Nysosis** [limbo-works/Limbo.Umbraco.Tables#3]
When a document containing a Limbo Table is saved, the value that is put into the External Examine index as the representation of the data for site search purposes is the full JSON structure of the table data:

![image](https://github.com/limbo-works/Limbo.Umbraco.Tables/assets/5476382/f61545ab-801a-446e-9f9d-8e9f3d8e67e9)

Which means if someone searches some of the property names, the page containg a table would come back unexpectedly (in the perspective of someone viewing the frontend):

![image](https://github.com/limbo-works/Limbo.Umbraco.Tables/assets/5476382/79cda5a6-7396-4145-8342-0607cc6a5584)

A custom `IPropertyIndexValueFactory` can be written and specified by [`TablesDataEditor.cs`](https://github.com/limbo-works/Limbo.Umbraco.Tables/blob/f1dca12b718324335fc522028b2f08450da3004b/src/Limbo.Umbraco.Tables/PropertyEditors/TablesDataEditor.cs#L11) to craft the value that gets entered to be only the plain text of the cell contents

**Comment by abjerner** [comment]
Hi @Nysosis 

I'm closing this issue as you've also created a PR for this. I will try to find some time looking into the PR 😉
