### ISSUE TITLE
Unable to add new columns after 11th column created using Version: 1.1.3

### ISSUE THREAD

**Issue by jattwood** [limbo-works/Limbo.Umbraco.Tables#31]
Very strange an intermittent issue with Version: 1.1.3 on Umbraco 11 that we have discovered with tables greater than 11 cells when the Limbo tables are used in the block grid. I can't confirm if this happens when not in the block grid, but I would image this issue exists there as well. Under certain scenarios, we are unable to add additional columns or delete rows when these conditions exist. No errors outputted to console.

To replicate:
1) Create a table with 1 row 12 cells.

![image](https://github.com/limbo-works/Limbo.Umbraco.Tables/assets/6452616/f30f035a-d237-4f95-9a45-a1003839ead7)

2) Label each cell with values. I use number 1 through 11, leave the 12th cell with no value.
3) Click create
4) Reopen the table block from your grid
5) Try to create another column, "Add Column" button does not work, delete row does not work

![image](https://github.com/limbo-works/Limbo.Umbraco.Tables/assets/6452616/df9fcb7e-9581-444b-a46d-75265f59aa9a)

Even if you add a value to your 12th cell, you can't add additional values. Also the delete row function does not work during this scenario.

You can bump the table to make it start working again by deleting a column, but then you lose the data in that entire column across the board, so it's not a viable workaround.

**Comment by jattwood** [comment]
Just working with this again. Regardless of what we do, we are unable to build a table greater than 12 columns. To recreate, just try to add new columns to a new table - click add column 11X to replicate. At the 12th column, you are unable to add any more columns.

**Comment by jattwood** [comment]
Can you please update line 28 in TableDataEditor.js to a number larger than 12? Maybe 24?

![image](https://github.com/limbo-works/Limbo.Umbraco.Tables/assets/6452616/f1e8cf36-bc13-4a44-92e3-be5351a8974f)

**Comment by hfloyd** [comment]
I'm bumping up against this issue today. As per a [prior conversation](https://github.com/limbo-works/Limbo.Umbraco.Tables/pull/29#issuecomment-2059506901)... @abjerner noticed the limitation and wasn't sure why it was in place, which leads me to believe it could be removed without any ill effects.

**Comment by jattwood** [comment]
Hey Heather! Yeah I did a PR fix for this. Just waiting on it's integration and release as well! Cheers.

**Comment by hfloyd** [comment]
Ah, I see your two PRs: 
https://github.com/limbo-works/Limbo.Umbraco.Tables/pull/32
https://github.com/limbo-works/Limbo.Umbraco.Tables/pull/33

I'm going to try merging your fix in the "v1" branch, since I need it fixed for a v10 site. (I just compile my own custom NuGet package from these fixes since I usually am too impatient to wait for official releases. 😉

**Comment by abjerner** [comment]
Sorry for the lack of action. I'm caught up in too many different things, so even small issues like this end up not being fixed/merged for waaaay too long. I'll try to find some time looking into this soon 😉

**Comment by abjerner** [comment]
I've now pushed new releases for both Umbraco 10 and 13:

- [`v1.0.4`](https://github.com/limbo-works/Limbo.Umbraco.Tables/releases/tag/v1.1.4) (Umbraco 10-12)
- [`v13.0.1`](https://github.com/limbo-works/Limbo.Umbraco.Tables/releases/tag/v13.0.1) (Umbraco 13)

**Comment by jattwood** [comment]
Awesome thanks. Heather - for Sprott lol...

**Comment by jattwood** [comment]
Thank you!
