### ISSUE TITLE
Add flag for header

### ISSUE THREAD

**Issue by Eaglef90** [limbo-works/Limbo.Umbraco.Tables#7]
Would it be possible to add a flag to setup a header (<thead>)?

**Comment by abjerner** [comment]
Could you elaborate this? I'm not sure what you're requesting.

**Comment by Eaglef90** [comment]
Right now there is an Add Row and Add column action which generates tr and td tags. And option to make a column/row into a header so a th is generated instead would be nice. This way we don't have to write custom code when we want a table header at the top of the table.

**Comment by abjerner** [comment]
This is already possible by enabling the **Use first column as header** flag:

![image](https://github.com/limbo-works/Limbo.Umbraco.Tables/assets/3634580/ae1851ed-ed6b-44b0-8e7b-3a146840006f)
