### ISSUE TITLE
Please add support for Umbraco 12

### ISSUE THREAD

**Issue by Eaglef90** [limbo-works/Limbo.Umbraco.Tables#9]
Umbraco 12 was just released, can you please update the package to support installing into a v12 of Umbraco?

**Comment by abjerner** [comment]
Hi @Eaglef90 

I've now pushed a new [**`v1.0.3`**](https://github.com/limbo-works/Limbo.Umbraco.Tables/releases/tag/v1.0.3) release so the NuGet package may now also be installed with Umbraco 12 😉
